# Generated by Django 3.2.7 on 2022-01-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writerID', models.PositiveIntegerField(null=True)),
                ('lab', models.CharField(max_length=40)),
                ('title', models.TextField()),
                ('postDate', models.DateField()),
                ('startDay', models.DateField()),
                ('endDay', models.DateField()),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('isOffline', models.BooleanField()),
                ('reward', models.PositiveSmallIntegerField()),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('content', models.TextField()),
                ('articleFile', models.FileField(blank=True, null=True, upload_to='')),
                ('articleImg', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expInfo', models.PositiveIntegerField()),
                ('pkUser', models.PositiveIntegerField()),
                ('startTime', models.PositiveSmallIntegerField()),
                ('endTime', models.PositiveSmallIntegerField()),
                ('isCheck', models.BooleanField(default=False)),
                ('day', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=15)),
                ('userPW', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=100)),
                ('birth', models.PositiveSmallIntegerField()),
                ('penalty', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('lab', models.CharField(blank=True, max_length=40)),
                ('isExp', models.BooleanField(default=False)),
                ('isPermit', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Article_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pkUser', models.PositiveIntegerField()),
                ('pkPost', models.PositiveIntegerField()),
                ('timeLength', models.PositiveIntegerField()),
            ],
        ),
    ]
