# Generated by Django 4.0 on 2022-01-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_ID', models.IntegerField()),
                ('title', models.TextField()),
                ('date', models.DateField()),
                ('During_Date', models.SmallIntegerField(default=0)),
                ('place', models.CharField(max_length=30)),
                ('body', models.TextField(max_length=1000)),
                ('post_file', models.FileField(upload_to='')),
                ('post_img', models.ImageField(upload_to='')),
                ('on_offline', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=15)),
                ('user_PW', models.CharField(max_length=15)),
                ('phone_num', models.CharField(max_length=11)),
                ('birth_year', models.PositiveSmallIntegerField()),
                ('user_money', models.PositiveSmallIntegerField()),
                ('warn_num', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('lab_name', models.CharField(blank=True, max_length=40)),
                ('verify_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User_Post_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_num', models.IntegerField()),
                ('Post_num', models.IntegerField()),
            ],
        ),
    ]
