# Generated by Django 4.0 on 2022-01-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_ID', models.PositiveIntegerField()),
                ('writer_pk', models.PositiveIntegerField()),
                ('lab_name', models.CharField(max_length=40)),
                ('title', models.TextField()),
                ('post_date', models.DateField()),
                ('exp_start', models.DateField()),
                ('exp_end', models.SmallIntegerField()),
                ('sub_age', models.PositiveSmallIntegerField()),
                ('sub_gender', models.BooleanField()),
                ('on_offline', models.BooleanField()),
                ('reward', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=30)),
                ('body', models.TextField(max_length=1000)),
                ('post_file', models.FileField(blank=True, upload_to='')),
                ('post_img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Time_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_info', models.PositiveIntegerField()),
                ('user_pk', models.PositiveIntegerField()),
                ('start', models.PositiveSmallIntegerField()),
                ('end', models.PositiveSmallIntegerField()),
                ('boolean', models.PositiveSmallIntegerField()),
                ('day', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=15)),
                ('user_PW', models.CharField(max_length=15)),
                ('phone_num', models.CharField(max_length=11)),
                ('birth_year', models.PositiveSmallIntegerField()),
                ('penalty', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=40)),
                ('lab_name', models.CharField(blank=True, max_length=40)),
                ('exp_submit', models.BooleanField(default=False)),
                ('permit', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User_Post_match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_pk', models.PositiveIntegerField()),
                ('post_pk', models.PositiveIntegerField()),
                ('time_length', models.PositiveIntegerField()),
            ],
        ),
    ]
