# Generated by Django 4.0 on 2022-01-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_gender',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='boolean',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='time_table',
            name='day',
            field=models.DateField(),
        ),
    ]
