# Generated by Django 3.2.7 on 2022-01-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_writer_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
